export default {
    GETHOMEBANNER: "GETHOMEBANNER",// 轮播图
    GETHOMEPLAYLIST: "GETHOMEPLAYLIST",// 推荐歌单
    GETHOMENEWSONG: "GETHOMENEWSONG",// 新歌速递
    GETHOMENEWDISC: "GETHOMENEWDISC",// 新碟上架
    GETHOMEMUSICEVENT: "GETHOMEMUSICEVENT",// 音乐活动
    GETHOMEMIGUPRODUCT: "GETHOMEMIGUPRODUCT",// 咪咕出品
}