export default {
    GETMUSICLOG: "GETMUSICLOG",//排行榜信息
    GETMUSICLIST: "GETMUSICLIST",//音乐榜
    GETVIDEOLIST: "GETVIDEOLIST",//影视榜
    GETNEIDILIST: "GETNEIDILIST",//内地榜
    GETGANGTAILIST: "GETGANGTAILIST",//港台榜
    GETUSLIST: "GETUSLIST",//欧美榜
    GETJANPNLIST: "GETJANPNLIST",//日韩榜

    GETMUSICTAG: "GETMUSICTAG",//音乐榜
}